openapi: 3.0.3
info:
  title: Not compliant OAS3 description document
  version: 1.0.0
paths:
  /resources:
    summary: ©
components:
  schemas:
    camelCaseComponent:
      type: object
    PascalCaseComponent1:
      type: object
      title: ©
    PascalCaseComponent2:
      type: object
      description: |
        ©