name: lint OAS3 description documents with Spectral

on:
  push:
    paths:
      - ./oas/**/*.yaml
      - .github/workflows/lint-oas3.yaml
      - .spectral.yaml
  workflow_dispatch:

jobs:
  spectral-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run oas:lint