name: validate custom Spectral rules

on:
  push:
    paths:
      - ./spectral_rules/**/*.yaml
      - .github/workflows/validate-custom-spectral-rules.yml
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run spectral:validate-rules